language: python

matrix:
    include:
        - os: linux
          python: 3.7
          dist: xenial
        - os: linux
          python: 3.6
        - os: linux
          python: 3.5
        - os: linux
          python: 3.4
        - os: linux
          python: 3.3
        - os: linux
          python: 2.7
        allow_failures:
        - os: osx
          language: generic
          env: TOXENV=py27
        - os: linux
          python: nightly
install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then pip install -r dev-requirements.txt --user ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then pip install -r dev-requirements.txt ; fi
  - python setup.py install
script:
  - python -m art testcov
  - python version_check.py
  - python -m cProfile -s cumtime art_profile.py
after_success:
  - codecov